package com.innovery.mpm.resource.implementations.util;

public class AIRCommands{

	public static final String AIR_COMMAND_SET = "SET:AIRSUB";
	public static final String AIR_COMMAND_DEL = "DELETE:AIRSUB";
	public static final String AIR_COMMAND_GET = "GET:AIRSUB";
	
	public final static String TRANSID = ":TRANSID,";
	public final static String MSISDN = ":MSISDN,";
	
	public final static String AIR_COMMAND_GET_ACCOUNTDETAILS = ":RETURNDATA,ACCOUNTDETAILS";
	public final static String AIR_COMMAND_GET_BALANCEANDDATE = ":RETURNDATA,BALANCEANDDATE";
	public final static String AIR_COMMAND_GET_ACCUMULATORS = ":RETURNDATA,ACCUMULATORS";
	public final static String AIR_COMMAND_GET_FAFLIST = ":REQUESTEDOWNER,3:RETURNDATA,FAFLIST";
	public final static String AIR_COMMAND_GET_PAM = AIR_COMMAND_GET_ACCOUNTDETAILS+":REQUESTPAMINFORMATIONFLAG,1";
	public final static String AIR_COMMAND_GET_PROMOTION = ":RETURNDATA,PROMOTIONPLANS";
	public final static String AIR_COMMAND_GET_SHAREACCOUNT = ":RETURNDATA,SHAREACCOUNT";
	
	public final static String AIR_COMMAND_RUN_PAM = ":ACTIONTYPE,RUNPAM:PAMSERVICEID,";
	
	public final static String AIR_COMMAND_SET_ACCUMULATORS = ":ACCUMULATOR,SET,ACCUMULATOR,";
	public final static String AIR_COMMAND_DEL_ACCUMULATORS = ":ACCUMULATOR,DEL,ACCUMULATOR,";
	public final static String AIR_COMMAND_SET_DEDICATED = ":ACTIONTYPE,UPDATEBALANCEANDDATE:TRANSACTIONCURRENCY,EUR:DEDICATEDACCOUNT,SET,DEDICATEDACCOUNTID,";
	public final static String AIR_COMMAND_DEL_DEDICATED = ":ACTIONTYPE,UPDATEBALANCEANDDATE:DEDICATEDACCOUNT,DEL,DEDICATEDACCOUNTID,";
	
	public final static String AIR_COMMAND_SET_FAF = ":FAF,DEF,OWNER,";
	public final static String AIR_COMMAND_DEL_FAF = ":FAF,DEL,OWNER,";
	
	public final static String AIR_COMMAND_SET_LANGUAGE = ":ACTIONTYPE,UPDATEACCOUNTDETAILS:LANGUAGE,";
	
	public final static String AIR_COMMAND_SET_OFFER = ":OFFER,SET,OFFERID,";
	public final static String AIR_COMMAND_DEL_OFFER = ":OFFER,DEL,OFFERID,";
	
	public final static String AIR_COMMAND_DEF_PAM = ":PAM,DEF,PAMSERVICEID,";
	public final static String AIR_COMMAND_SET_PAM = ":PAM,SET,PAMSERVICEID,";
	public final static String AIR_COMMAND_DEL_PAM = ":PAM,DEL,PAMSERVICEID,";
	
	public final static String AIR_COMMAND_DEF_PROMOTION = ":PROMOTIONPLAN,DEF,PROMOTIONPLANID,";
	
	public final static String AIR_COMMAND_SET_SERVICECLASS = ":SERVICECLASSNEW,";
	
	public final static String AIR_COMMAND_SERVICEOFFERINGS = ":SERVICEOFFERINGS";
	public final static String AIR_COMMAND_SERVICEOFFERINGSID = ",SET,SERVICEOFFERINGID,";
	public final static String AIR_COMMAND_SET_SERVICEOFFERINGS = AIR_COMMAND_SERVICEOFFERINGS+AIR_COMMAND_SERVICEOFFERINGSID;
	
	public final static String AIR_COMMAND_SET_SHAREACCOUNT = ":SHAREACCOUNT,SET";
	public final static String AIR_COMMAND_DEL_SHAREACCOUNT = ":SHAREACCOUNT,DEL,UTID,";
	
	
	public final static String PARAMETER_ACCOUNTGROUPID = ":ACCOUNTGROUPID,";
	
	public final static String PARAMETER_ACCUMULATORS_STARTDATE = ",ACCUMULATORSTARTDATE,";
	public final static String PARAMETER_ACCUMULATORS_ENDDATE = ",ACCUMULATORENDDATE,";
	public final static String PARAMETER_ACCUMULATORS_ABS_VALUE = ",ACCUMULATORVALUEABSOLUTE,";
	public final static String PARAMETER_ACCUMULATORS_REL_VALUE = ",ACCUMULATORVALUERELATIVE,";
	
	public final static String PARAMETER_COMMUNITY_NEW = ":COMMUNITYIDLISTNEW,";
	public final static String PARAMETER_COMMUNITY_OLD = ":COMMUNITYIDLISTOLD,";
	public final static String PARAMETER_COMMUNITY_LIST = "COMMUNITYIDLIST";
	
	public final static String PARAMETER_DEDICATED_UNIT = ",DEDICATEDACCOUNTUNIT,";
	public final static String PARAMETER_DEDICATED_ABS_EXPIRYDATE = ",DEDICATEDEXPIRYDATE,";
	public final static String PARAMETER_DEDICATE_ABS_VALUE = ",DEDICATEDACCOUNTVALUENEW,";
	public final static String PARAMETER_DEDICATE_REL_VALUE = ",DEDICATEDACCOUNTVALUERELATIVE,";
	public final static String PARAMETER_DEDICATED_REL_EXPIRYDATE = ",ADJUSTMENTDATERELATIVE,";
	
	public final static String PARAMETER_FAF_KINDIKATOR = ",KINDICATOR,";
	public final static String PARAMETER_FAF_NUMBER = ",FAFNUMBER,";
	public final static String PARAMETER_FAF_OWNER = "1";
	
	public final static String PARAMETER_BALANCEANDDATE = ":ACTIONTYPE,UPDATEBALANCEANDDATE";
	
	public final static String PARAMETER_TRANSACTION = ":TRANSACTIONCURRENCY,EUR";
	public final static String PARAMETER_BALANCE_POSITIVE_ADJ = PARAMETER_BALANCEANDDATE+":ADJUSTMENTAMOUNTRELATIVE,";
	public final static String PARAMETER_BALANCE_NEGATIVE_ADJ = PARAMETER_BALANCEANDDATE+":ADJUSTMENTAMOUNTRELATIVE,-";
	
	public final static String PARAMETER_OFFER_ABS_STARTDATE = ",STARTDATE,";
	public final static String PARAMETER_OFFER_ABS_EXPIRYDATE = ",EXPIRYDATE,";
	public final static String PARAMETER_OFFER_REL_STARTDATE = ",STARTDATERELATIVE,";
	public final static String PARAMETER_OFFER_REL_EXPIRYDATE = ",EXPIRYDATERELATIVE,";
	public final static String PARAMETER_OFFER_TYPE = ",OFFERTYPE,";
	
	
	public final static String PARAMETER_PAMCLASS = ",PAMCLASSID,";
	public final static String PARAMETER_PAMCLASS_NEW = ",PAMCLASSIDNEW,";
	public final static String PARAMETER_PAMCLASS_OLD = ",PAMCLASSIDOLD,";
	public final static String PARAMETER_PAMSCHED = ",SCHEDULEID,";
	public final static String PARAMETER_PAMSCHED_NEW = ",SCHEDULEIDNEW,";
	public final static String PARAMETER_PAMSCHED_OLD = ",SCHEDULEIDOLD,";
	public final static String PARAMETER_PAMPERIOD = ",CURRENTPAMPERIOD,";
	public final static String PARAMETER_PAMDATE = ",DEFERREDTODATE,";
	public final static String PARAMETER_PAMPRIORITY = ",PAMSERVICEPRIORITY,";
	public final static String PARAMETER_PAMPRIORITY_NEW = ",PAMSERVICEPRIORITYNEW,";
	public final static String PARAMETER_PAMPRIORITY_OLD = ",PAMSERVICEPRIORITYOLD,";
	
	public final static String PARAMETER_PROMOTION_STARTDATE = ",PROMOTIONSTARTDATE,";
	public final static String PARAMETER_PROMOTION_ENDDATE = ",PROMOTIONENDDATE,";
	public final static String PARAMETER_DEL_PROMOTION_START_OLD = ":PROMOTIONPLAN,DEL,PROMOTIONSTARTDATEOLD,";
	public final static String PARAMETER_DEL_PROMOTION_END_OLD = ",PROMOTIONENDDATEOLD,";
	
	public final static String PARAMETER_SERVICEOFFERINGS_FLAG = ",SERVICEOFFERINGFLAG,";
	public final static String PARAMETER_SERVICEOFFERINGS_FLAG_ON = PARAMETER_SERVICEOFFERINGS_FLAG+"1";
	public final static String PARAMETER_SERVICEOFFERINGS_FLAG_OFF = PARAMETER_SERVICEOFFERINGS_FLAG+"0";
	
	public final static String PARAMETER_UC = ",UCID,";
	public final static String PARAMETER_UC_ABS_VALUE = ",UCMVALUENEW,";
	public final static String PARAMETER_UC_REL_VALUE = ",AUCMVALUERELATIVE,";
	public final static String PARAMETER_UT = ",UTID,";
	public final static String PARAMETER_UT_ABS_VALUE = ",UTMVALUENEW,";
	
	public final static String PARAMETER_SIMEXP_ABS_EXPIRYDATE = ":SFEEEXPDATE,";
	public final static String PARAMETER_SIMEXP_REL_EXPIRYDATE = ":SFEEEXPDATERELATIVE,";
	public final static String PARAMETER_SUPEXP_ABS_EXPIRYDATE = ":SUPEXPDATE,";
	public final static String PARAMETER_SUPEXP_REL_EXPIRYDATE = ":SUPEXPDATERELATIVE,";
 			
	public final static String END = ";";
}
